[general]
import = [
	"~/.config/alacritty/themes/gruvbox_material_dark.toml"
]

[terminal.shell]
program="/usr/bin/zsh"

[font]
size=12

	[font.normal]
	family = "FiraMono Nerd Font"

[window]
startup_mode = "windowed"
dimensions = { columns = 120, lines = 50 } 
dynamic_padding = true
opacity = 1.0
