
[font]
size = 14

[font.normal]
family = "Mononoki Nerd Font"

[terminal.shell]
program = "zsh"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "windowed"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 2
y = 2

[general]
import = ["/home/olli/.config/alacritty/themes/cyberdream.toml"]
