[general]
import = [
	"~/.config/alacritty/themes/gruvbox_material_dark.toml"
]

[terminal.shell]
program="/usr/bin/zsh"

[font]
size=14

	[font.normal]
	family = "Mononoki Nerd Font"

[window]
startup_mode = "windowed"
dimensions = { columns = 120, lines = 50 } 
dynamic_padding = true
opacity = 1.0
padding = { x = 2, y = 2 }
